#!/bin/bash
#\
ulimit -n 128 ;\
exec tclsh "$0" "$@"

package require xoshell

set language [ ::xodsl::Language newLanguage ]
set environment [ $language set environment ]

set fileName [ lindex $argv 0 ]
set doHistory [ lindex $argv 1 ]

if { "$doHistory" == "" } { set doHistory 1 }

if [ string match *.tcl $fileName ] {
    set name [ string range $fileName 0 end-4 ]
} else {
    set name $fileName
}

if [ file exists $fileName ] {

set shell [ ::xoshell::Shell new -environment $environment \
                                    -language $language \
                                    -name $name \
                                    -fileName $fileName \
                                    -doHistory $doHistory  ] 
$shell executeScript
$shell writeHistory

} else {

set shell [ ::xoshell::Shell new -environment $environment \
                                    -language $language \
                                    -name $name \
                                    -fileName $fileName \
                                    -doHistory $doHistory  ] 
$shell shell
$shell writeHistory

}

