#!/bin/bash
#\
ulimit -n 128 ;\
exec tclsh "$0" "$@"


package require xounit
package require xoexception

if { [ llength $argv ] == 0 } {

   puts "Usage: runDocCoverage PACKAGENAME \[PACKAGENAME\] ..."
   puts "Example: runDocCoverage xox"
   puts "Example: runDocCoverage xox xounit xoexception"

   exit
}

eval ::xounit::RunDocCoverage new $argv

